In [1]:
#Activity log
#Bolortulga Seded
#18/02/2026
#Week 2 - Task 1: Working with Missing data - Employees.csv

In [14]:
import pandas as pd
import numpy as np
df = pd.read_csv('employees.csv')

In [15]:
print(df.isnull().sum())

First Name            67
Gender               145
Start Date             0
Last Login Time        0
Salary                 0
Bonus %                0
Senior Management     67
Team                  43
dtype: int64

In [16]:
bool_series = pd.isnull(df['Gender'])
print(df[bool_series])

    First Name Gender  Start Date Last Login Time  Salary  Bonus %  \
20        Lois    NaN   4/22/1995         7:18 PM   64714    4.934
22      Joshua    NaN    3/8/2012         1:58 AM   90816   18.816
27       Scott    NaN   7/11/1991         6:58 PM  122367    5.218
31       Joyce    NaN   2/20/2005         2:40 PM   88657   12.752
41   Christine    NaN   6/28/2015         1:08 AM   66582   11.308
..         ...    ...         ...             ...     ...      ...
961    Antonio    NaN   6/18/1989         9:37 PM  103050    3.050
972     Victor    NaN   7/28/2006         2:49 PM   76381   11.159
985    Stephen    NaN   7/10/1983         8:10 PM   85668    1.909
989     Justin    NaN   2/10/1991         4:58 PM   38344    3.794
995      Henry    NaN  11/23/2014         6:09 AM  132483   16.655

    Senior Management                  Team
20               True                 Legal
22               True       Client Services
27              False                 Legal
31              False               Product
41               True  Business Development
..                ...                   ...
961             False                 Legal
972              True                 Sales
985             False                 Legal
989             False                 Legal
995             False          Distribution

[145 rows x 8 columns]

In [6]:
print(df.isna())

     First Name  Gender  Start Date  Last Login Time  Salary  Bonus %  \
0         False   False       False            False   False    False
1         False   False       False            False   False    False
2         False   False       False            False   False    False
3         False   False       False            False   False    False
4         False   False       False            False   False    False
..          ...     ...         ...              ...     ...      ...
995       False    True       False            False   False    False
996       False   False       False            False   False    False
997       False   False       False            False   False    False
998       False   False       False            False   False    False
999       False   False       False            False   False    False

     Senior Management   Team
0                False  False
1                False   True
2                False  False
3                False  False
4                False  False
..                 ...    ...
995              False  False
996              False  False
997              False  False
998              False  False
999              False  False

[1000 rows x 8 columns]

In [17]:
nmg = pd.notnull(df['Gender'])
display(df[nmg])

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
994,George,Male,6/21/2013,5:47 PM,98874,4.479,True,Marketing
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [10]:
df["Gender"] = df["Gender"].fillna('No Gender')
print(df[10:25])

   First Name     Gender  Start Date Last Login Time  Salary  Bonus %  \
10     Louise     Female   8/12/1980         9:01 AM   63241   15.132
11      Julie     Female  10/26/1997         3:19 PM  102508   12.637
12    Brandon       Male   12/1/1980         1:08 AM  112807   17.492
13       Gary       Male   1/27/2008        11:40 PM  109831    5.831
14   Kimberly     Female   1/14/1999         7:13 AM   41426   14.543
15    Lillian     Female    6/5/2016         6:09 AM   59414    1.256
16     Jeremy       Male   9/21/2010         5:56 AM   90370    7.369
17      Shawn       Male   12/7/1986         7:45 PM  111737    6.414
18      Diana     Female  10/23/1981        10:27 AM  132940   19.082
19      Donna     Female   7/22/2010         3:48 AM   81014    1.894
20       Lois  No Gender   4/22/1995         7:18 PM   64714    4.934
21    Matthew       Male    9/5/1995         2:12 AM  100612   13.645
22     Joshua  No Gender    3/8/2012         1:58 AM   90816   18.816
23        NaN       Male   6/14/2012         4:19 PM  125792    5.042
24       John       Male    7/1/1992        10:08 PM   97950   13.873

   Senior Management             Team
10              True              NaN
11              True            Legal
12              True  Human Resources
13             False            Sales
14              True          Finance
15             False          Product
16             False  Human Resources
17             False          Product
18             False  Client Services
19             False          Product
20              True            Legal
21             False        Marketing
22              True  Client Services
23               NaN              NaN
24             False  Client Services

In [13]:
data = pd.read_csv("employees.csv")
data = data.replace(to_replace=np.nan, value=-99)
print(data[10:25])

   First Name  Gender  Start Date Last Login Time  Salary  Bonus %  \
10     Louise  Female   8/12/1980         9:01 AM   63241   15.132
11      Julie  Female  10/26/1997         3:19 PM  102508   12.637
12    Brandon    Male   12/1/1980         1:08 AM  112807   17.492
13       Gary    Male   1/27/2008        11:40 PM  109831    5.831
14   Kimberly  Female   1/14/1999         7:13 AM   41426   14.543
15    Lillian  Female    6/5/2016         6:09 AM   59414    1.256
16     Jeremy    Male   9/21/2010         5:56 AM   90370    7.369
17      Shawn    Male   12/7/1986         7:45 PM  111737    6.414
18      Diana  Female  10/23/1981        10:27 AM  132940   19.082
19      Donna  Female   7/22/2010         3:48 AM   81014    1.894
20       Lois     -99   4/22/1995         7:18 PM   64714    4.934
21    Matthew    Male    9/5/1995         2:12 AM  100612   13.645
22     Joshua     -99    3/8/2012         1:58 AM   90816   18.816
23        -99    Male   6/14/2012         4:19 PM  125792    5.042
24       John    Male    7/1/1992        10:08 PM   97950   13.873

   Senior Management             Team
10              True              -99
11              True            Legal
12              True  Human Resources
13             False            Sales
14              True          Finance
15             False          Product
16             False  Human Resources
17             False          Product
18             False  Client Services
19             False          Product
20              True            Legal
21             False        Marketing
22              True  Client Services
23               -99              -99
24             False  Client Services

In [12]:
df = pd.DataFrame({
    "A": [12, 4, 5, None, 1],
    "B": [None, 2, 54, 3, None],
    "C": [20, 16, None, 3, 8],
    "D": [14,3, None, None, 6]
})
print(df)
df.interpolate(method='linear', limit_direction='forward')

      A     B     C     D
0  12.0   NaN  20.0  14.0
1   4.0   2.0  16.0   3.0
2   5.0  54.0   NaN   NaN
3   NaN   3.0   3.0   NaN
4   1.0   NaN   8.0   6.0

      A     B     C     D
0  12.0   NaN  20.0  14.0
1   4.0   2.0  16.0   3.0
2   5.0  54.0   9.5   4.0
3   3.0   3.0   3.0   5.0
4   1.0   3.0   8.0   6.0

In [19]:
df = pd.read_csv("employees.csv")
nd = df.dropna(axis=0, how='any')
print("Old data frame lenght:", len(df))
print("New data frame lenght:", len(nd))
print("Rows with at least one missing value:", len(df) - len(nd))

Old data frame lenght: 1000
New data frame lenght: 764
Rows with at least one missing value: 236